### ISSUE TITLE
Failed to setup cluster topology

### ISSUE THREAD

**Issue by krisis** [heketi/vagrant-heketi#2]
I tried to follow the instructions provided in the README. I performed a POST request to http://192.168.10.100:8080/nodes with the following request body,
`{ "name" : "192.168.10.100", "zone": "1" }`
It failed with Response Body (raw) "request unable to be parsed" with the following Response Header.

`
    Status Code: 422 status code 422
    Content-Length: 28
    Content-Type: text/plain; charset=utf-8
    Date: Mon, 29 Jun 2015 13:27:14 GMT
`

Note: I am using a libvirt (instead of VirtualBox) provided setup. The setup worked fine. GET request on `http://192.168/10.100/nodes` returned empty list of nodes as expected.

**Comment by lpabon** [comment]
Ah yes, I need to update the README.  Zone is an _int_.  It needs to be:

```
{ "name" : "192.168.10.100", "zone": 1 }
```

**Comment by krisis** [comment]
Ah, I didn't notice that either :-(

**Comment by krisis** [comment]
This issue no longer exists with the updated instructions in README. Marking this issue as closed. Thanks for the speedy resolution.
